- name: Set up local workstation
  gather_facts: true
  hosts: local
  become: no
  roles:
    - role: zsh
      tags:
        - zsh
    - role: zimfw
      tags:
        - zimfw
    - role: asdf
      tags:
        - asdf
    - role: docker
      tags:
        - docker
    - role: golang
      tags:
        - golang
