- name: Installs zsh | apt
  become: yes
  become_user: root
  apt:
    name: zsh
    state: present

- name: Installs curl | apt
  become: yes
  become_user: root
  apt:
    name: curl
    state: present

- name: Sets zsh as default shell for my user | command
  become: yes
  become_user: root
  command: chsh -s /bin/zsh {{ ansible_env.USER }}
  register: zsh_for_user
  failed_when: zsh_for_user.rc >= 1
  changed_when: zsh_for_user.rc == 0

# - name: Sets zsh as default shell for my user | shell
#   user:
#     name: "{{ ansible_env.USER }}"
#     shell: /usr/bin/zsh
#   become: yes
#   when: zsh_for_user.rc == 0